services:
  postgres:
    image: postgres:latest
    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: remindme

    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
