services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    volumes:
      - postgres-data:/var/lib/postgresql

  bot:
    depends_on:
      - postgres

    build:
      dockerfile: Dockerfile
    restart: unless-stopped

    env_file: .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  postgres-data:
