services:
  postgres:
    image: postgres:latest
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: remindme

    volumes:
      - postgres-data:/var/lib/postgresql

  bot:
    depends_on:
      - postgres

    build:
      dockerfile: Dockerfile
    restart: unless-stopped

    env_file: .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: remindme

volumes:
  postgres-data:
