token: "${DISCORD_TOKEN}"
public_key: "${DISCORD_PUBLIC_KEY}"
port: "${PORT:9876}"

db:
  host: "${POSTGRES_HOST:localhost}"
  port: "${POSTGRES_PORT:5432}"
  database: "${POSTGRES_DATABASE:postgres}"
  username: "${POSTGRES_USERNAME:postgres}"
  password: "${POSTGRES_PASSWORD:password}"
