token: "${DISCORD_TOKEN}"

db:
  host: "${POSTGRES_HOST:localhost}"
  port: "${POSTGRES_PORT:5432}"
  database: "${POSTGRES_DATABASE:postgres}"
  username: "${POSTGRES_USERNAME:postgres}"
  password: "${POSTGRES_PASSWORD:password}"
