# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
#   sqlc-gen-better-python v0.4.4
"""Module containing models."""
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "Reminder",
)

import msgspec
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import datetime


class Reminder(msgspec.Struct):
    """Model representing Reminder.

    Attributes
    ----------
    id : int
    user_id : int
    description : str
    expire_at : datetime.datetime
    reference_message_id : int | None
    reference_channel_id : int | None
    reference_guild_id : int | None
    handled : bool

    """

    id: int
    user_id: int
    description: str
    expire_at: datetime.datetime
    reference_message_id: int | None
    reference_channel_id: int | None
    reference_guild_id: int | None
    handled: bool
